In [13]:
import numpy as np

In [14]:
x = np.array([0.5, 0.8])
t = np.array([0, 1, 0])

In [15]:
np.random.seed(1)
W = np.random.randn(2, 3)
#b = np.random.randn(1,)
W

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ]])

In [16]:
def net(x):
  #print('net W', W)
  return np.dot(x, W)
  #return np.dot(x, W)+b

In [17]:
a = net(x)

In [18]:
def softmax(x):
  c = np.max(x)
  y = np.exp(x-c)/np.sum(np.exp(x-c))
  #print('softmax=', y)
  return y

In [19]:
y = softmax(a)

In [20]:
def cross_entropy_error(y, t):
  if y.ndim == 1:
    batch_size = 1
    #print('batch_size=', batch_size)
  else:
    batch_size = y.shape[0]
    #print('batch_size=', batch_size)
  return -np.sum(t*np.log(y+1e-7))/batch_size

In [21]:
cross_entropy_error(y, t)

0.5490175021267665

In [22]:
def loss(x, t):
  z = net(x)
  y = softmax(z)
  loss = cross_entropy_error(y, t)
  #print('loss 함수에서 loss값 리턴:', loss)
  return loss

In [23]:
def f(W):
  return loss(x, t)

In [24]:
import numpy as np

h = 1e-4                           # W = (W11, W21, W31
grad = np.zeros((2, 3))            #     W12, W22, W32)
#print('initial grad', grad)

for idr, r in enumerate(W):     # (0, W1 W2 W3)  0은 인덱스
  #print(r, '\n')
  for idx in range(r.size):
    #print('\n시작:', r[idx])
    tmp = r[idx]
    
    r[idx] = tmp+h                         
    #print('W값의 변화', W)
    fxh1 = f(W)                                  #f(W+h)   
    #print('fxh1값',  fxh1)
    
    #print('W값의 변화 2', W)  
    r[idx] = tmp-h                               #f(W-h)
    fxh2 = loss(x, t)
    #print('fxh2값',  fxh2)

    grad[idr, idx]=(fxh1-fxh2)/(2*h)
    r[idx] = tmp                               # 원래 W값으로 변경
    #print(grad[idr, idx])                        # for문 통해 W 전체 기울기 값으로 변경

grad

#array([[ 1.62434536, -0.61175641, -0.52817175],
#       [-1.07296862,  0.86540763, -2.3015387 ]])

array([[ 0.18734281, -0.21124154,  0.02389873],
       [ 0.29974849, -0.33798647,  0.03823798]])